<a href="https://colab.research.google.com/github/orazioc17/numpy-pandas/blob/master/numpy_array.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

In [ ]:
lista = [1, 2, 3, 4, 5, 6, 7, 8, 9]
lista

[1, 2, 3, 4, 5, 6, 7, 8, 9]

In [ ]:
arr = np.array(lista)

In [ ]:
type(arr)

numpy.ndarray

In [ ]:
matriz = [[1,2,3], [4,5,6], [7,8,9]]
matriz = np.array(matriz)
matriz

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [ ]:
arr[0]

1

In [ ]:
matriz[0, 2]

3

In [ ]:
# Slicing con numpy
print(arr[1:6])
print(arr[:5])
print(arr[3:])
print(arr[::3])

[2 3 4 5 6]
[1 2 3 4 5]
[4 5 6 7 8 9]
[1 4 7]


In [ ]:
print(arr[-1])  # Ultima posicion
print(arr[-3:])  # Desde la 3era posicion de derecha a izquierda hasta el final del array

9
[7 8 9]


In [ ]:
# Slicing con matrices
print(matriz[1:])
print(matriz[1: , 0:2])

[[4 5 6]
 [7 8 9]]
[[4 5]
 [7 8]]
